var _topic;

chrome.storage.sync.get('adTopic', function(topic) {

    _topic = topic.adTopic;

    console.log('this is in the search file', _topic);

    window.location.href = 'https://www.google.com/';

    var _formArray = document.querySelectorAll('form');


    var searchArrays = {
        travel: ["Travel to Spain",
                "trip to spain",
                "flights to spain",
                "best restaurant in spain",
                "learn spanish",
                "visit barcelona",
                "visit spain",
                "guide spain travel",
                "guided trips to spain",
                "hotels in madrid",
                "best cities in spain to visit",
                "travel spain",
                "spain travel",
                "travel to spain",
                "spain holidays",
                "visit spain",
                "trip to spain",
                "spain tourism",
                "spain travel guide",
                "travel in spain",
                "tour of spain",
                "traveling to spain",
                "spain vacation",
                "spain trip",
                "tours of spain",
                "trips to spain",
                "spain tour",
                "spain vacation packages",
                "visiting spain",
                "tour spain",
                "places to visit in spain",
                "traveling in spain",
                "places in spain",
                "spain vacations",
                "vacation in spain",
                "tourism in spain",
                "travelling to spain",
                "spain holiday packages",
                "tourism spain",
                "spain tourist attractions",
                "spain holiday destinations",
                "spain travel packages",
                "tours in spain",
                "spain destinations",
                "holiday destinations in spain",
                "spain tourist",
                "travelling in spain",
                "traveling spain",
                "spain trips",
                "where to go in spain",
                "tourist attractions in spain",
                "best places to visit in spain",
                "touring spain",
                "vacations in spain",
                "tourist places in spain",
                "spain places to visit",
                "spain attractions",
                "spanish holiday destinations",
                "vacation to spain",
                "route planner spain",
                "cheap holiday packages to spain",
                "vacation packages to spain",
                "spain tourist information",
                "vacation spain",
                "places to see in spain",
                "travel guide spain",
                "spain cities",
                "where to visit in spain",
                "holiday packages to spain",
                "where to travel in spain",
                "things to do in spain",
                "travelling spain",
                "spain visit",
                "spanish tourism",
                "vacations to spain",
                "information on spain",
                "planning a trip to spain",
                "flights spain",
                "tour to spain",
                "travel packages to spain",
                "go spain",
                "go to spain",
                "places to go in spain",
                "spain tour guide",
                "spain tour packages",
                "spain guide",
                "what to visit in spain",
                "spanish vacation",
                "best places in spain",
                "attractions in spain",
                "spain travel guides",
                "spain information",
                "what to see in spain",
                "tour in spain",
                "plan a trip to spain",
                "visit to spain",
                "spain trip planner",
                "sightseeing in spain",
                "travel guide to spain",
                "spanish travel",
                "spain travel agency",
                "spain tourist places",
                "best of spain",
                "best holiday destinations in spain",
                "packages to spain",
                "northern spain travel",
                "travel to spain cheap",
                "spain tours 2014",
                "holiday destinations spain",
                "spain travel information",
                "trip spain",
                "spain tour package",
                "airfare to spain",
                "flight tickets to spain",
                "spain tourist guide",
                "travel spanish",
                "travel agency spain",
                "guided tours of spain",
                "fly to spain",
                "tourist in spain",
                "best place to visit in spain",
                "spain travel deals",
                "places to visit spain",
                "destinations in spain",
                "spain travel advice",
                "spain travel brochure",
                "best spain travel guide",
                "places of interest in spain",
                "spain packages",
                "holiday packages spain",
                "things to see in spain",
                "spain travel info",
                "vacation packages spain",
                "travel guides spain",
                "best places to holiday in spain",
                "trips to spain packages",
                "spain package",
                "what to do in spain",
                "tourism of spain",
                "tourist spain",
                "spain tours packages",
                "spain vacation package",
                "spanish tour",
                "spain tourist sites",
                "tourist information spain",
                "spanish travel agency",
                "spain cities to visit",
                "spain travel guide book",
                "spain travel destinations",
                "information of spain",
                "travel deals to spain",
                "spain travels",
                "air tickets to spain",
                "spain traveling",
                "popular holiday destinations in spain",
                "tourist destinations in spain",
                "spain vacation spots",
                "rail travel spain",
                "guided tours spain",
                "vacationing in spain",
                "best spain tours",
                "info on spain",
                "travel through spain",
                "cities to visit in spain",
                "tour guide spain",
                "best places to go in spain",
                "cheap travel to spain",
                "travel guide for spain",
                "spain tourism guide",
                "place to visit in spain",
                "flight deals to spain",
                "spanish tourist office",
                "trip in spain",
                "spanish tourist information",
                "where to go on holiday in spain",
                "spain travel agent",
                "spain travel tours",
                "best places to go on holiday in spain",
                "spain tourism website",
                "spain travel guide 2013",
                "guide to spain",
                "spanish destinations",
                "travel china",
                "vacation spots in spain",
                "air travel",
                "cheap spain vacations",
                "southern spain travel",
                "spain vacation deals",
                "best places to travel in spain",
                "travel insurance",
                "spain travel package",
                "spain tours",
                "tourist sites in spain",
                "spain tourism places",
                "travel europe",
                "new zealand travel",
                "australia travel",
                "travel italy",
                "spain places",
                "ireland travel",
                "interesting places in spain",
                "alaska travel",
                "best travel deals",
                "luxury travel",
                "travel brazil",
                "travel deals",
                "travelling through spain",
                "adventure travel",
                "travel greece",
                "costa rica travel",
                "travel germany",
                "cheap travel",
                "spain tourist map",
                "travel agent spain",
                "cheap trip to spain",
                "travel russia",
                "hawaii travel",
                "travel south america",
                "airlines to spain",
                "travel sites",
                "travel agents",
                "travel map",
                "vacations spain",
                "last minute travel",
                "spain travel agents",
                "spain holiday destinations guide",
                "cheap flights to spain",
                "travel france",
                "international travel",
                "travel packages",
                "cheap travel deals",
                "spain vacation tours",
                "a trip to spain",
                "best spanish holiday destinations",
                "travel",
                "travel asia",
                "travel japan",
                "travel destinations in spain",
                "flights to spain",
                "thailand travel",
                "tour packages to spain",
                "travel agent",
                "travel argentina",
                "airfare spain",
                "best destinations in spain",
                "nice places in spain",
                "tourist attraction in spain",
                "spain sightseeing",
                "popular places in spain",
                "travel websites",
                "best vacation spots in spain",
                "tour guide in spain",
                "holiday packages in spain",
                "fly spain",
                "travel southern spain",
                "tour guide in spanish",
                "tourist spots in spain",
                "spain holiday",
                "top destinations in spain",
                "cruise travel",
                "travel advice spain",
                "spain travelling",
                "top 10 places to visit in spain",
                "spanish guide",
                "travel around spain",
                "madrid spain travel",
                "travel mexico",
                "india travel",
                "tour guides in spain",
                "espana travel",
                "travel portugal",
                "plan trip to spain",
                "holiday destination in spain",
                "top holiday destinations in spain",
                "best holiday destinations spain",
                "cheap spanish holiday destinations",
                "places to go on holiday in spain",
                "south spain holiday destinations",
                "spain tour packages from usa",
                "travels to spain",
                "south of spain holiday destinations",
                "traveling through spain",
                "spain where to go",
                "spain where to visit",
                "flight spain",
                "discount travel",
                "best place to vacation in spain",
                "travel northern spain",
                "holiday destinations in spain for families",
                "spain tourism map",
                "southern spain holiday destinations",
                "travel canada",
                "tourist guide spain",
                "spain and travel",
                "travel switzerland",
                "travel agency",
                "northern spain travel guide",
                "best holiday destination in spain",
                "best place in spain",
                "tourist place in spain",
                "trips in spain",
                "travel information on spain",
                "travels in spain",
                "best place to go in spain",
                "travelling around spain",
                "travel spain cheap",
                "holiday places in spain",
                "best season to visit spain",
                "tour spanish",
                "spain trips package",
                "best holiday destinations in spain for families",
                "best places to see in spain",
                "spain travel agencies",
                "spain guides",
                "best spain destinations",
                "travel taiwan",
                "travel within spain",
                "south spain travel",
                "holiday packages for spain",
                "cheap travel spain",
                "spain tourist spots",
                "weekend trips to spain",
                "budget travel spain",
                "spanish travel brochure",
                "cheap ticket to spain",
                "spain travel sites",
                "touring in spain",
                "best travel guide for spain",
                "trip planner spain",
                "ticket spain",
                "lonely planet guide to spain",
                "family holiday destinations in spain",
                "tourist guide to spain",
                "best spain travel guide book",
                "destinations spain",
                "spain tourist destinations",
                "spain trips 2014",
                "best places to vacation in spain",
                "spain best places to visit",
                "planning trip to spain",
                "budget travel",
                "air travel to spain",
                "southern spain travel guide",
                "world travel",
                "best tourist places in spain",
                "where to visit spain",
                "train travel in spain",
                "travel spain itinerary",
                "cheapest way to travel in spain",
                "guided tours in spain",
                "travel deals spain",
                "explore spain",
                "places in spain to go on holiday",
                "where to vacation in spain",
                "spanish holiday packages",
                "travel inn",
                "travel packages spain",
                "top spanish holiday destinations",
                "places to visit in northern spain",
                "rail travel europe",
                "spain tourist office",
                "tours to spain",
                "travel guide",
                "tours around spain",
                "spain for tourists",
                "group travel spain",
                "spain tourist info",
                "rail travel in spain",
                "spain visiting places",
                "adventure travel spain",
                "cheapest way to travel to spain",
                "airlines spain",
                "airline spain",
                "best places to visit spain",
                "train travel",
                "cheap travel in spain",
                "tour in spanish",
                "spanish travel guides",
                "top spain destinations",
                "travel tours to spain",
                "اسبانيا سياحة",
                "tourist info spain",
                "tourist cities in spain",
                "spain travel book",
                "spain guide book",
                "travel brochure for spain",
                "china travel",
                "south of spain travel",
                "spanish trips",
                "good holiday destinations in spain",
                "south spain tours",
                "ontario travel",
                "places to visit in madrid spain",
                "tour to spain from usa",
                "trips in spanish",
                "southern spain tourism",
                "spain best places",
                "spain places of interest",
                "interesting places to visit in spain",
                "best places in spain to go on holiday",
                "bus travel in spain",
                "spain top destinations",
                "guided tour spain",
                "spain vacation destinations",
                "northern spain holiday destinations",
                "places to travel in spain",
                "top 5 places to visit in spain",
                "best spanish holiday destinations for families",
                "guided tour of spain",
                "tour packages spain",
                "tour operators in spain",
                "spanish trip",
                "asia travel",
                "travel madrid spain",
                "spain holiday guide",
                "best vacation in spain",
                "top ten places to visit in spain",
                "spain holiday destination",
                "cheap vacation packages to spain",
                "cheap places to go in spain",
                "tourist attractions spain",
                "travel agents for spain",
                "travel brochure spain",
                "touring southern spain",
                "tickets spain",
                "cheap holiday packages spain",
                "spain tourist cities",
                "travel tours spain",
                "stay in spain",
                "sites to see in spain",
                "travel advisor spain",
                "tours for spain",
                "student travel",
                "visit espana",
                "spanish travel agent",
                "holiday destination spain",
                "best trip to spain",
                "best trips to spain",
                "spain trips cheap",
                "cheapest place to go in spain",
                "places to visit in southern spain",
                "spain sightseeing attractions",
                "trips spain",
                "southern spain destinations",
                "spanish vacation spots",
                "tours through spain",
                "travel information spain",
                "best place to travel in spain",
                "spain travel planner",
                "spanish travel sites",
                "air tickets spain",
                "top 10 places in spain",
                "package tour spain",
                "sights to see in spain",
                "spanish tour guide",
                "travel brochure of spain",
                "information about spain",
                "tourist map spain",
                "lonely planet guide spain",
                "famous places in spain",
                "tourist attractions of spain",
                "south spain tourism",
                "vacations in spanish",
                "испания",
                "spanish tourist resorts",
                "travel agencies spain",
                "spain touring",
                "spain tourist attraction",
                "spain sightseeing places",
                "travel to southern spain",
                "cheap airline tickets to spain",
                "tour around spain",
                "cheap travel europe",
                "spanish travel agents in spain",
                "espana tour",
                "spanish tourist",
                "spain holiday packages 2013",
                "package trips to spain",
                "madrid spain tourist attractions",
                "tourist destination in spain",
                "places to visit in spain in may",
                "spanish travel guide",
                "cheap tickets spain",
                "tours spain",
                "tours espana",
                "spain what to see",
                "spain where to go on holiday",
                "book a trip to spain",
                "travel austria",
                "tourist spot in spain",
                "touristic places in spain",
                "nice holiday destinations in spain",
                "spain sites to visit",
                "tourism to spain",
                "where to go spain",
                "budget travel to spain",
                "travel agency spanish",
                "trips to southern spain",
                "popular spanish holiday destinations",
                "family holiday destinations spain",
                "trip packages to spain",
                "attractions of spain",
                "popular tourist destinations in spain",
                "best spain vacation",
                "nice places to visit in spain",
                "spain holidays packages",
                "spain place to visit",
                "spain and tourism",
                "espana tourism",
                "getting around spain",
                "group travel to spain",
                "best spain holiday destinations",
                "tourist places of spain",
                "top places in spain",
                "cheap destinations in spain",
                "top attractions in spain",
                "north spain holiday destinations",
                "cheap vacations spain",
                "travel in southern spain",
                "places to visit in spain in september",
                "top cities to visit in spain",
                "vacation destinations in spain",
                "holidays packages to spain",
                "best way to travel to spain",
                "best cities in spain for tourist",
                "places to go to in spain",
                "traveling to spain on a budget",
                "spain destination",
                "train travel spain",
                "traveling around spain",
                "places to visit in spain and portugal",
                "travel to spain in april",
                "south spain tour",
                "spain brochure tourism",
                "best places in spain for holidays",
                "cheap holiday destinations in spain",
                "lonely planet spain",
                "family travel",
                "i want to travel to spain",
                "vacation tours spain",
                "best vacation spot in spain",
                "best places to visit in northern spain",
                "spanish tourist attractions",
                "spain travel companies",
                "top 10 destinations in spain",
                "travel central america",
                "tourist locations in spain",
                "attraction in spain",
                "spain travel ideas",
                "top spain holiday destinations",
                "spain best holiday destinations",
                "nice places to go in spain",
                "vacation places in spain",
                "places to see in spain and portugal",
                "famous places to visit in spain",
                "cheap vacations in spain",
                "spain vacations packages",
                "travel guide northern spain",
                "cities of spain to visit",
                "places to go spain",
                "sites to visit in spain",
                "spain travel tips",
                "go for spain",
                "spanish holiday destinations top ten",
                "spanish tourist board",
                "spain travel map",
                "spain travel plan",
                "vacation cities in spain",
                "best place to holiday in spain",
                "vacations to spain deals",
                "spain travel tour packages",
                "us travel",
                "the best places to visit in spain",
                "flight tickets spain",
                "spain tourism office",
                "best place in spain for holiday",
                "place to visit spain",
                "cheap spain trips",
                "tourist areas in spain",
                "top tourist destinations in spain",
                "fun things to do in spain",
                "trip around spain",
                "madrid spain tours",
                "top destinations spain",
                "top 10 spanish holiday destinations",
                "spain sites to see",
                "travel españa",
                "south spain travel guide",
                "cheapest holiday packages to spain",
                "top 10 tourist attractions in spain",
                "spanish guides",
                "top holiday destinations spain",
                "holiday destinations in southern spain",
                "spain places to see",
                "spanish travel websites",
                "top vacation spots in spain",
                "popular places to visit in spain",
                "spain train travel",
                "spain adventure travel",
                "top tourist attractions in spain",
                "best tourist destinations in spain",
                "world travel guide spain",
                "cheap holiday packages in spain",
                "touring sites in spain",
                "places to tour in spain",
                "travel insurance spain",
                "main tourist attractions in spain",
                "last minute flights spain",
                "best holiday destination spain",
                "spain as a tourist destination",
                "vacation package to spain",
                "tourist map of spain",
                "places to go in spain for holiday",
                "visiting southern spain",
                "spanish tours",
                "best tourist place in spain",
                "best destination in spain",
                "tour operators spain",
                "good places to go in spain",
                "best place to visit spain",
                "visiting places in spain",
                "traveling spain on a budget",
                "top 10 tourist destinations in spain",
                "travel planner spain",
                "best destinations spain",
                "best travel book for spain",
                "travel tour spain",
                "travel book spain",
                "information for spain",
                "spain information for tourists",
                "good places to visit in spain",
                "испания туроператор",
                "best places to visit in spain and portugal",
                "places of interest spain",
                "map of spain holiday destinations",
                "best places to see in spain and portugal",
                "spain guidebooks",
                "spain tourist attractions top 10",
                "tourist places spain",
                "where to go in spain in may",
                "great places to visit in spain",
                "10 best places to visit in spain",
                "top 10 spain destinations",
                "famous tourist places in spain",
                "10 places to visit in spain",
                "top 10 holiday destinations in spain",
                "travel north spain",
                "spanish tourist destinations",
                "trip to spain and portugal",
                "visiting spain in july",
                "tour sites in spain",
                "spain to go",
                "sightseeing spain",
                "guide spain",
                "best vacation spots spain",
                "spain places to go",
                "travel plan spain",
                "discount travel canada",
                "cheapest place to fly into spain",
                "famous tourist attractions in spain",
                "spain budget travel",
                "beautiful places to visit in spain",
                "cities to see in spain",
                "destination in spain",
                "historical sites in spain",
                "travel agents spain",
                "north spain tourism",
                "north spain travel",
                "important places to visit in spain",
                "best spain vacations",
                "most visited places in spain",
                "cheapest flights spain",
                "destination spain",
                "where to go in southern spain",
                "best spain travel book",
                "bus travel spain",
                "most popular places in spain",
                "top 10 attractions in spain",
                "popular destinations in spain",
                "places to see spain",
                "most popular places to visit in spain",
                "tourist information northern spain",
                "about spain",
                "spain tourist place",
                "what to see in spain and portugal",
                "travel advice for spain",
                "spain top attractions",
                "tourism spanish",
                "good places in spain",
                "cheap fares to spain",
                "spain things to do",
                "best holiday places in spain",
                "spain best destinations",
                "holiday locations in spain",
                "top spanish destinations",
                "amazing places in spain",
                "lonely planet spanien",
                "travel to spain in december",
                "places to holiday in spain",
                "discount flights to spain",
                "spain tourist map cities",
                "top ten destinations in spain",
                "travel lodge",
                "spain resort guide",
                "tourist sights in spain",
                "north spain tours",
                "best places to travel to in spain",
                "spain.com",
                "things to visit in spain",
                "best holiday destinations in spain for couples",
                "travel south spain",
                "the best place to visit in spain",
                "best spanish destinations",
                "spain travel directory",
                "place to go in spain",
                "popular tourist attractions in spain",
                "travelling within spain",
                "places to visit southern spain",
                "top destination in spain",
                "flights from spain",
                "tour guide spanish",
                "famous sites in spain",
                "travel and tourism in spain",
                "north west spain tourism",
                "plane tickets spain",
                "best places to visit in spain in may",
                "travel in spain and portugal",
                "top 5 places visit spain",
                "major tourist attractions in spain",
                "places to visit in south spain",
                "spain attractions top 10",
                "top travel destinations in spain",
                "spain tourism bureau",
                "best place to go on holiday in spain",
                "tourists attractions in spain",
                "spain tourist spot",
                "spain vacation cities",
                "top 10 tourist places in spain",
                "important places in spain",
                "spanish on the go",
                "spanish tourist places",
                "travel map of spain",
                "cheapest place to visit in spain",
                "famous attractions in spain",
                "airline tickets spain",
                "cheap places to visit in spain",
                "tourists places in spain",
                "spain lonely planet",
                "top ten places in spain",
                "spain sites",
                "top tourist cities in spain",
                "nice place in spain",
                "best place in spain to go on holiday",
                "fun places to go in spain",
                "travel direction",
                "spain best tourist places",
                "5 places to visit in spain",
                "tourists sites in spain",
                "spanish tourist guide",
                "tourist destinations spain",
                "places to visit in spain in june",
                "historical places in spain",
                "sites in spain",
                "best sightseeing in spain",
                "place to see in spain",
                "which city to visit in spain",
                "best destinations in spain for couples",
                "popular holiday resorts in spain",
                "places to visit in south of spain",
                "spain tourist destination",
                "vacation package spain",
                "places of spain",
                "spain locations to visit",
                "top ten cities in spain",
                "best places in spain for holiday",
                "spain tourist areas",
                "spain holiday places",
                "spain top tourist attractions",
                "most popular destinations in spain",
                "3 places to visit in spain",
                "travel holland",
                "places to visit in north spain",
                "best tourist attractions in spain",
                "fun places to visit in spain",
                "spain holiday locations",
                "travel guides in spanish",
                "best locations in spain",
                "travelling spain on a budget",
                "ispaniya",
                "best tourist cities in spain",
                "cities to visit spain",
                "best attractions in spain",
                "top ten tourist attractions in spain",
                "place in spain",
                "spanish tourist sites",
                "spain tourist attractions list",
                "spain interesting places to visit",
                "airfares to spain",
                "air travel europe",
                "spanish info",
                "spain main tourist attractions",
                "northern spain guide",
                "major attractions in spain",
                "best holiday spain",
                "the best place in spain",
                "sightseeing places in spain",
                "top 10 cities to visit in spain",
                "cool places to visit in spain",
                "tourist activities in spain",
                "places in spain to visit",
                "best places to go to in spain"
            ],
        fitness: [
            "best treadmills",
            "good treadmills",
            "buy a treadmill",
            "gyms near me",
            "cheap gym memberships",
            "work out classes",
            "soul cycle",
            "flywheel",
            "spin classes",
            "best spin classes",
            "spinn class",
            "fitness",
            "fitness equipment",
            "fitness exercise",
            "sports fitness",
            "health fitness",
            "fitness goods",
            "sporting goods fitness",
            "fitness 24",
            "hour fitness",
            "24 hour fitness",
            "first fitness",
            "fitness training",
            " la fitness",
            "fitness stuff",
            "fitness exercise equipment",
            "Glute Exercises",
            "Calf Exercises",
            "Hamstring workout",
            "Bicep Exercises",
            "free weights",
            "how to bench press",
            "Neck Exercises",
            "Chest Exercises",
            "crossfit",
            "Yoga",
            "zumba",
            "insanity workout",
            "p90x",
            "couch to 5k",
            "kettlebells",
            "squat challenge",
            "planks",
            "diet",
            "lose weight",
            "health food",
            "how to lose weight",
            "train for marathon",
            "fitness magazine",
            "fitness magazines",
            "fit magazine",
            "magazine fitness",
            "health and fitness magazine",
            "health & fitness magazine",
            "health and fitness magazines",
            "health fitness magazine",
            "fitness trainer magazine",
            "fitness and health magazines",
            "top fitness magazines",
            "fitness magazine articles",
            "fitness advertisements in magazines",
            "fitness health magazine",
            "on fitness magazine",
            "fitness and health magazine",
            "fit magazines",
            "men’s fitness magazine",
            "health fitness magazines",
            "training and fitness magazine",
            "fitness magazines list",
            "health & fitness magazines",
            "magazines fitness",
            "fitness woman magazine",
            "male fitness magazine",
            "personal trainer",
            "online personal trainer",
            "find personal trainer",
            "certified personal trainer",
            "personal trainer certification",
            "find a personal trainer",
            "personal trainers",
            "personal trainer training",
            "home personal trainer",
            "aerobics",
            "aerobic exercise",
            "aerobic exercises",
            "aerobic fitness",
            "aerobics workout",
            "aerobic workouts",
            "aerobic workout",
            "aerobics fitness",
            "health and fitness",
            "fitness and health",
            "health fitness",
            "health & fitness",
            "health and fitness tips",
            "fitness health",
            "health fitness articles",
            "fitness for health",
            "health and fitness information",
            "health and fitness center",
            "fitness & health",
            "health and fitness advice",
            "health and fitness videos",
            "health and fit",
            "health fitness information",
            "health fitness plan",
            "workout plans",
            "workout plan",
            "good workout plans",
            "great workout plans",
            "a good workout plan",
            "good workout plan",
            "full workout plan",
            "workouts plans",
            "a workout plan",
            "plan workout",
            "i need a workout plan",
            "how to plan a workout",
            "need a workout plan",
            "the workout plan",
            "new workout plans",
            "great workout plan",
            "workout routines",
            "workout routine",
            "daily workout routine",
            "full body workout routine",
            "a workout routine",
            "weekly workout routine",
            "great workout routines",
            "upper body workout routine",
            "routine workout",
            "workouts routines",
            "new workout routines",
            "effective workout routines",
            "workout routine program",
            "i need a workout routine",
            "top workout routines",
            "different workout routines",
            "workout routine planner",
            "i need a new workout routine",
            "kettlebell workout routines",
            "workout routines to build muscle",
            "great workout routine",
            "need a workout routine",
            "effective workout routine",
            "gym workout",
            "gym workouts",
            "workout gyms",
            "workout gym",
            "workouts for the gym",
            "gym workout guide",
            "nutrition for gym workout",
            "workouts for gym",
            "gym workout planner",
            "workouts gym",
            "fitness club",
            "fitness clubs",
            "club fitness",
            "health and fitness club",
            "health and fitness clubs",
            "fitness club membership",
            "fitness health clubs",
            "fitness health club",
            "health fitness club",
            "health & fitness clubs",
            "fitness equipment",
            "home fitness equipment",
            "fitness equipments",
            "health fitness equipment",
            "commercial fitness equipment",
            "used fitness equipment",
            "discount fitness equipment",
            "buy fitness equipment",
            "fitness exercises",
            "fitness exercise",
            "exercise and fitness",
            "exercise fitness",
            "fitness and exercise",
            "exercise for fitness",
            "fitness exercise programs",
            "exercises for fitness",
            "exercise fitness programs",
            "exercise & fitness",
            "physical fitness exercise",
            "fitness exercise equipment",
            "fit exercise program",
            "fitness exercise program",
            "exercise equipment fitness",
            "exercises fitness",
            "fitness & exercise",
            "fit exercises",
            "physical fitness exercise at home",
            "fitness programs",
            "fitness program",
            "fitness training programs",
            "fitness training program",
            "physical fitness program",
            "health fitness programs",
            "health and fitness program",
            "fitness gyms",
            "fitness gym",
            "gym fitness",
            "gym and fitness",
            "fitness gym equipment",
            "fitness gyms in my area",
            "fitness websites",
            "fitness website",
            "health and fitness websites",
            "best fitness websites",
            "top fitness websites",
            "best fitness website",
            "health and fitness website",
            "physical fitness websites",
            "health fitness websites",
            "website fitness",
            "fitness training websites",
            "fit website",
            "website for fitness",
            "best health and fitness websites",
            "fitness and nutrition websites",
            "fitness and health websites",
            "fitness information website",
            "top health and fitness websites",
            "fitness gym website",
            "fitness related websites",
            "best fitness websites for women",
            "workout program",
            "workout programs",
            "workout training program",
            "workouts programs",
            "program workout",
            "great workout programs",
            "fitness online",
            "online fitness",
            "online fitness trainer",
            "online fitness training",
            "online fitness magazine",
            "fitness online magazine",
            "best fitness online",
            "sports and fitness online",
            "women s fitness magazine",
            "fitness women",
            "women s fitness",
            "women fitness",
            "fitness magazines for women",
            "fitness for women",
            "fitness programs for women",
            "women fitness magazines",
            "women in fitness",
            "women s fitness and health",
            "fitness womens",
            "womens fitness magazine",
            "women fitness magazine",
            "womens fitness training",
            "fitness for women magazine",
            "best fitness magazines for women",
            "womens fitness",
            "best fitness magazine for women",
            "fitness magazine women",
            "abs workout",
            "ab workouts",
            "abs exercise",
            "ab exercise",
            "abs workouts",
            "abs exercises",
            "best workout",
            "best workout routine",
            "best workouts",
            "best workout program",
            "best workout programs",
            "the best workout routine",
            "best workout routines",
            "best gym workouts",
            "best workout plan",
            "the best workout routines",
            "best workout plans",
            "best fitness workouts",
            "best workout videos",
            "best workout regimen",
            "the best workout program",
            "work out",
            "work out routine",
            "work out schedule",
            "work out exercises",
            "work out fitness",
            "work out tips",
            "work out exercise",
            "work out planner",
            "working out routines",
            "working out schedule",
            "work out website",
            "work out center",
            "work out regime",
            "work out centers",
            "a work out routine",
            "work out sites",
            "work out regimen for women",
            "work out magazines",
            "fitness training",
            "health and fitness training",
            "physical fitness training",
            "fitness training programme",
            "fitness weight training",
            "personal fitness training",
            "fitness strength training",
            "gym programs",
            "gym program",
            "gym training program",
            "gym workout program",
            "gym workout programs",
            "gym training programs",
            "gym exercise program",
            "best gym program",
            "gym workouts programs",
            "workout programs for the gym",
            "best gym programs",
            "program for workout in gym",
            "gym exercises program",
            "best gym training program",
            "program for gym training",
            "gym exercise programs",
            "program for gym workout",
            "workout program for gym",
            "exercise plan",
            "exercise plans",
            "fitness exercise plan",
            "exercise training plan",
            "exercises plan",
            "workout plans for women",
            "workout routines for women",
            "workout programs for women",
            "workouts for women",
            "workout routine for women",
            "women workout routines",
            "women workouts",
            "workout women",
            "workout magazines for women",
            "best workout routine for women",
            "best workout plan for women",
            "women workout",
            "best workout routines for women",
            "workout for women",
            "work out plans",
            "work out plan",
            "work out plans for men",
            "best work out plans",
            "working out plan",
            "work out a plan",
            "workout plans that work",
            "i need a work out plan",
            "personal training",
            "online personal training",
            "personal training programs",
            "personal training studio",
            "personal training program",
            "exercise routine",
            "exercise routines",
            "exercise routines for women",
            "routine exercise",
            "exercising routines",
            "exercises routines",
            "new exercise routines",
            "health club",
            "health clubs",
            "health club membership",
            "health club website",
            "the health club",
            "gym health club",
            "health club websites",
            "24 hour health club",
            "exercise workouts",
            "workout exercises",
            "exercise workout",
            "exercise workout plan",
            "workout exercise",
            "exercise workout plans",
            "exercise fitness workout",
            "exercise workout routines",
            "fitness exercise workouts",
            "fitness workouts & exercises",
            "fitness workouts and exercises",
            "fitness workout exercises",
            "exercise workout programs",
            "workout routines exercises",
            "exercise workout schedule",
            "workouts exercises",
            "workouts and exercises",
            "schedule for exercise & workouts",
            "exercise workout program",
            "fitness workout",
            "fitness workouts",
            "fitness workout plan",
            "fitness workout program",
            "fitness workout programs",
            "fitness workout plans",
            "workout fitness program",
            "fitness training workouts",
            "workout fitness plan",
            "good fitness workouts",
            "physical fitness workouts",
            "workouts fitness",
            "workout for fitness",
            "workouts for fitness",
            "fitness workout planner",
            "fit workout program",
            "gym workout routines",
            "gym workout routines for women",
            "gym workout routine",
            "gym routines",
            "gym exercise routine",
            "workout routines for the gym",
            "daily gym workout routine",
            "best gym workout routine",
            "best gym routine",
            "work out gym routines",
            "good gym workout routine",
            "workout routine for the gym",
            "exercise routine for gym",
            "gym daily workout routine",
            "workout gym routines",
            "gym exercise routines",
            "gym workouts routines",
            "workout routine for gym",
            "workout routine gym",
            "workout routines for gym",
            "gym exercise routine for women",
            "exercise routines for the gym",
            "gym workout routine for women",
            "routine for gym",
            "good gym workout routines",
            "gym training routine",
            "muscle and fitness",
            "muscle fitness",
            "muscle builder",
            "muscle workout",
            "build muscle",
            "muscle building",
            "muscle mass",
            "muscle growth",
            "gain muscle",
            "how to build muscle",
            "building muscle mass",
            "workout schedule",
            "gym workout schedule",
            "best workout schedule",
            "workout schedules",
            "good workout schedule",
            "fitness workout schedule",
            "best gym workout schedule",
            "a good workout schedule",
            "daily gym workout schedule",
            "gym workout schedules",
            "gym workout plan",
            "gym plan",
            "gym exercise plan",
            "gym workout plans",
            "gym fitness plan",
            "workout plans for the gym",
            "gym training plan",
            "work out plans for the gym",
            "workout plan for the gym",
            "exercise plan for gym",
            "daily gym workout plan",
            "workout plan for gym",
            "good workout plans for the gym",
            "work out plan for gym",
            "best gym workout plan",
            "i need a workout plan for the gym",
            "workout plans for gym",
            "work out plan for the gym",
            "exercise plans for the gym",
            "exercise plan for the gym",
            "workout gym plan",
            "workout plan gym",
            "full gym workout plan",
            "gym exercise plan for women",
            "gym work out plans",
            "fitness trainer",
            "fitness trainers",
            "fitness personal trainer",
            "personal fitness trainers",
            "personal fitness trainer",
            "fitness trainer certification",
            "personal fitness trainer certification",
            "certified fitness trainer",
            "good workouts",
            "good workout routines",
            "good workout routine",
            "a good workout routine",
            "good workout programs",
            "good workout program",
            "i need a good workout routine",
            "workouts for men",
            "workout plans for men",
            "workout programs for men",
            "mens workout",
            "mens workout magazines",
            "boot camp workout",
            "fitness boot camp",
            "boot camp fitness",
            "fitness boot camps",
            "fitness camp",
            "home workout",
            "home workouts",
            "at home workouts",
            "home workout routines",
            "workout at home",
            "workout routines for men",
            "workout routine for men",
            "gym workout routines for men",
            "work out routine for men",
            "good workout routines for men",
            "24 hr fitness",
            "24 fitness",
            "fitness 24 hours",
            "24 hour fitness centers",
            "24 hour fitness center",
            "24 fitness center",
            "24 hour fitness.com",
            "fitness and nutrition",
            "fitness nutrition",
            "nutrition and fitness articles",
            "health fitness and nutrition",
            "nutrition for fitness training",
            "health and fitness nutrition",
            "nutrition for fitness and sport",
            "work out programs",
            "work out program",
            "work out programs for men",
            "work out training programs",
            "working out programs",
            "exercise gym",
            "gym exercises",
            "gym exercise",
            "best gym exercises",
            "gym exercises schedule",
            "upper body workout",
            "body workout",
            "full body workouts",
            "body workouts",
            "workout body",
            "total body workout",
            "fitness instructor",
            "fitness instructors",
            "fitness instructor certification",
            "fitness instructor course",
            "fitness instructor training",
            "fitness routines",
            "fitness routine",
            "fitness workout routines",
            "fitness training routine",
            "fitness workout routine",
            "fitness exercise routines",
            "best fitness routine",
            "weight lifting workouts",
            "weight workouts",
            "weights workout routine",
            "workout weights",
            "weight lifting workout",
            "weights workout plan",
            "weight training workout",
            "weight workout routines",
            "weight loss workout video",
            "weight loss workout",
            "weight workout",
            "weight training workouts",
            "in shape magazine",
            "exercise magazine",
            "workout magazines",
            "gym magazine",
            "exercise magazines",
            "workout magazine",
            "weight magazines",
            "gym magazines",
            "exercise magazines for women",
            "fitness sites",
            "fitness site",
            "health and fitness sites",
            "best fitness sites",
            "fitness sites online",
            "top fitness sites",
            "online fitness sites",
            "best fitness",
            "best fitness programs",
            "best fitness magazine",
            "best fitness magazines",
            "best fitness plans",
            "24 hour gyms",
            "24 gym",
            "24 hr gym",
            "24 fitness gym",
            "24 hr gyms",
            "24 hrs gym",
            "health exercises",
            "health fitness exercise",
            "exercise for health and fitness",
            "exercise health and fitness",
            "exercise for fitness and health",
            "health and fitness exercise",
            "health articles on exercise and fitness",
            "health fitness and exercise",
            "exercise and health magazine",
            "weight training equipment",
            "body weight training",
            "weight training exercises",
            "weight training program",
            "weight training programs",
            "good exercise routine",
            "good exercise routines",
            "a good exercise routine",
            "good exercise program",
            "good exercises routine",
            "good exercise plan",
            "good exercise plans",
            "healthy fitness",
            "healthy and fitness",
            "healthy fitness plan",
            "healthy fit gym",
            "fitness healthy",
            "gym programme",
            "gym training programme",
            "gym programmes",
            "gym training programmes",
            "training programmes for the gym",
            "gym workout programme",
            "fitness programs for men",
            "mens fitness magazine",
            "men s fitness magazine",
            "mens muscle and fitness magazine",
            "fitness training programs for men",
            "best exercise programs",
            "best exercise routine",
            "best exercise program",
            "best exercise plan",
            "best exercise routines",
            "best health magazine",
            "health magazine online",
            "best health magazine for women",
            "best health magazines",
            "best health magazines for women",
            "bodybuilding program",
            "bodybuilding workout",
            "bodybuilding tips",
            "bodybuilding training",
            "bodybuilding exercises",
            "bodybuilding programs",
            "bodybuilding workouts",
            "gym",
            "home gym",
            "gym equipment",
            "gyms",
            "gym membership",
            "home gym equipment",
            "home gyms",
            "local gyms",
            "gym memberships near me",
            "gym training",
            "gym memberships",
            "find a gym",
            "gym locator",
            "gym information",
            "gym training schedule",
            "gym sites",
            "local gym",
            "gym classes",
            "gym regime",
            "gym site",
            "fitness tips",
            "fitness shop",
            "fitness centers",
            "fitness center",
            "fitness plan",
            "fitness classes",
            "fitness articles",
            "fitness ball",
            "sport fitness",
            "home fitness",
            "fitness dvd",
            "fitness machine",
            "fitness videos",
            "cardio fitness",
            "fitness machines",
            "fitness plans",
            "fitness centre",
            "total fitness",
            "fitness bike",
            "fitness gear",
            "fitness video",
            "fitness programme",
            "fitness sport",
            "family fitness",
            "fitness store",
            "fitness centres",
            "get fit",
            "fitness studio",
            "kids fitness",
            "fitness products",
            "personal fitness",
            "fitness sports",
            "senior fitness",
            "fitness information",
            "female fitness",
            "fitness membership",
            "fitness weights",
            "ladies fitness",
            "fitness books",
            "fitness class",
            "fitness web",
            "fitness woman",
            "on fitness",
            "fitnesses",
            "fitness station",
            "fitness studios",
            "sports fitness",
            "fitness software",
            "fitness dvds",
            "fitness franchise",
            "fitness certification",
            "fitness courses",
            "fitness wear",
            "corporate fitness",
            "weight fitness",
            "fitness clothing",
            "fitness apparel",
            "fitness bootcamp",
            "diet fitness",
            "fitness page",
            "fitness music",
            "fitnes fit",
            "fitness coach",
            "www.fitness",
            "horizon fitness",
            "web fitness",
            "the fitness center",
            "man fitness",
            "fitness course",
            "fitness spa",
            "pilates fitness",
            "www.fitness.com",
            "fitness jobs",
            "fitness education",
            "weider fitness",
            "fitness ernährung",
            "life fitness",
            "outdoor fitness",
            "boxing fitness",
            "vision fitness",
            "fit fitnes",
            "fitness mags",
            "yoga fitness",
            "fitness publications",
            "york fitness",
            "fitness together",
            "fitness en espanol",
            "fitness con",
            "fitness planner 2014",
            "elite fitness",
            "fitness and",
            "pregnancy fitness",
            "womans fitness",
            "aquatic fitness",
            "exercise equipment",
            "exercise bikes",
            "exercises",
            "exercise videos",
            "exercise machines",
            "cardio exercise",
            "exercise machine",
            "exercise programs",
            "exercise tips",
            "exercise program",
            "exercise video",
            "toning exercises",
            "home exercise",
            "fat burning exercise",
            "physical training exercises",
            "exercise programs for women",
            "home exercise equipment",
            "exercise website",
            "exercise bike",
            "exercise dvd",
            "exercise ball",
            "exercise classes",
            "stomach exercise",
            "pilates exercises",
            "latest exercise videos",
            "exercises programs",
            "latest exercise",
            "pilates exercise",
            "stomach exercises",
            "weight lifting exercises",
            "abdominal exercises",
            "exercise training schedule",
            "workouts",
            "workout",
            "workout equipment",
            "cardio workout",
            "cardio workouts",
            "20 minute workout",
            "30 minute workout",
            "leg workouts",
            "arm workouts",
            "core workouts",
            "workout planner",
            "workout tips",
            "dumbbell workouts",
            "dumbbell workout",
            "workout training",
            "circuit training workouts",
            "workout websites",
            "workout regimen",
            "online workout",
            "core workout",
            "fat burning workout",
            "workout website",
            "workout diet",
            "workout programme",
            "workout book",
            "how to workout",
            "workout guide",
            "workout facility near me",
            "workout videos",
            "workout centers",
            "treadmill workouts",
            "online workouts",
            "workout site",
            "strength workouts",
            "toning workout",
            "workout video",
            "pilates workout",
            "the workout",
            "online workout sites",
            "ball workout",
            "workout regimens",
            "top workout websites",
            "treadmill workout",
            "health workout",
            "fitness",
            "weight lifting equipment",
            "get in shape",
            "video fitnes",
            "treadmills",
            "lifting routines",
            "weights",
            "sports training",
            "fitnesstraining",
            "fitnessstudios",
            "best training routine"
            ],
        school:[
            "graduate schools",
            "get an mba",
            "graduate school business",
            "graduate school education",
            "masters degree",
            "where to get masters degree",
            "post secondary education",
            "go back to school",
            "phd programs",
            "phd",
            "university of",
            "online masters degrees",
            "get a masters online",
            "online education",
            "coursera",
            "ed x",
            "online education",
            "online education degree",
            "continuing education",
            "online classes",
            "online schools",
            "online school",
            "online schooling",
            "school online",
            "schools online",
            "online school programs",
            "online education schools",
            "online schooling for college",
            "online school courses",
            "online education school",
            "it schools online",
            "online college schools",
            "online it schools",
            "online schools for education",
            "a online school",
            "online schooling programs",
            "online school classes",
            "online school education",
            "online college schooling",
            "online school from",
            "online college school",
            "online school college",
            "online in school",
            "online schools college",
            "top online schools",
            "online high schools",
            "college schools online",
            "online high school courses",
            "it online schools",
            "online high school classes",
            "college school online",
            "school online college",
            "online school search",
            "online schooling college",
            "tops online school",
            "online school website",
            "schools that offer online classes",
            "education schools online",
            "online undergraduate schools",
            "good online schools for education",
            "college online schools",
            "top online schools for education",
            "schools with online programs",
            "online school of education",
            "online school learning",
            "schools with online classes",
            "online school program",
            "school of education online",
            "distance learning",
            "distance learning phd",
            "distance learning colleges",
            "distance learning college",
            "phd distance learning",
            "distance learning schools",
            "long distance learning",
            "accredited distance learning",
            "best distance learning",
            "distance learning school",
            "distance learning programmes",
            "distance learning certificate",
            "distance learning master",
            "mba distance learning",
            "distance learning mba",
            "distance learning uk",
            "distance learning center",
            "distance learning diploma",
            "what is distance learning",
            "online classes",
            "online class",
            "classes online",
            "online education classes",
            "class online",
            "it classes online",
            "online it classes",
            "education classes online",
            "free online classes",
            "online learning classes",
            "a online classes",
            "it online classes",
            "online education class",
            "online classes for educators",
            "online class website",
            "u of u online classes",
            "distance education",
            "online distance education",
            "distance education programs",
            "long distance education",
            "distance education online",
            "distance education schools",
            "mba distance education",
            "distance education mba",
            "distance education school",
            "online learning",
            "learning online",
            "learn online",
            "online distance learning",
            "distance learning online",
            "best online learning",
            "it learning online",
            "online learning website",
            "online learning site",
            "online degree learning",
            "online learning degree",
            "free online learning",
            "online learning center",
            "what is online learning",
            "online website learning",
            "online learning degrees",
            "online college courses",
            "college courses online",
            "college online courses",
            "online college course",
            "college course online",
            "colleges online courses",
            "best online college courses",
            "online colleges courses",
            "colleges with online courses",
            "courses online colleges",
            "take college courses online",
            "online courses college",
            "best online colleges",
            "best online courses",
            "best online education",
            "best online degrees",
            "the best online colleges",
            "best online college",
            "best online degree",
            "best online education sites",
            "best online course",
            "the best online college",
            "best it college online",
            "best online courses to take",
            "best online it colleges",
            "online masters programs",
            "online masters degree",
            "masters degree online",
            "online masters degree programs",
            "online masters in education",
            "online master degree programs",
            "online masters degrees",
            "masters in education online",
            "master degree online",
            "online master degree",
            "masters degrees online",
            "online masters degree in education",
            "master of education online",
            "online education masters",
            "online master degrees",
            "online masters of education",
            "online masters education",
            "online master of education",
            "online master",
            "masters of education online",
            "online masters degrees in education",
            "online masters degree program",
            "online masters degree education",
            "master degree online program",
            "online master degree program",
            "online master degree in education",
            "online education degrees",
            "online education degree",
            "education degrees online",
            "online degree education",
            "education degree",
            "online education degree programs",
            "online degrees in education",
            "online degree in education",
            "degree in education",
            "education degree online",
            "degree in education online",
            "early childhood education online degree",
            "online education college degree",
            "online special education degree",
            "education online degree",
            "online education degree program",
            "education degrees",
            "online degrees education",
            "best online education degrees",
            "education online degrees",
            "early childhood education degree online",
            "online colleges for education degrees",
            "degree online education",
            "online classes for education degree",
            "education degree programs online",
            "degree education online",
            "best online education degree programs",
            "online university courses",
            "university courses",
            "university online courses",
            "university courses online",
            "online courses university",
            "online university course",
            "online course university",
            "university online course",
            "universities online courses",
            "online courses universities",
            "university course online",
            "internet university courses",
            "online courses from universities",
            "online universities courses",
            "online college degrees",
            "college degrees",
            "college degree",
            "online college degree",
            "college degrees line",
            "college degree online",
            "colleges with online degrees",
            "college degrees online",
            "college online degrees",
            "online degree colleges",
            "college online degree",
            "online degree college",
            "online degree programs",
            "online degree program",
            "best online degree programs",
            "online degrees programs",
            "degree programs online",
            "degree programs from online",
            "degree online programs",
            "degree program",
            "degree program online",
            "degree programs",
            "find online degree programs",
            "complete online degree programs",
            "best online degrees programs",
            "online degree programs that",
            "online as degree programs",
            "distance learning courses",
            "distance education courses",
            "distance courses",
            "distance learning course",
            "online distance learning courses",
            "courses distance learning",
            "open courses",
            "open course",
            "online open courses",
            "open courses online",
            "open course online",
            "open college courses online",
            "online open course",
            "open course university",
            "open courses university",
            "open online university courses",
            "online education courses",
            "education courses online",
            "online education course",
            "education online courses",
            "online educational courses",
            "education courses",
            "online courses in education",
            "online continuing education courses",
            "online courses education",
            "online special education courses",
            "online courses for educators",
            "educational courses online",
            "online course education",
            "online certificate courses",
            "online certificate programs",
            "online certificate",
            "best online certificate programs",
            "online certification",
            "online certificates",
            "online certification courses",
            "certificate online programs",
            "online education certificate",
            "free online courses with certificates",
            "online education certification",
            "accredited online colleges",
            "accredited online schools",
            "accredited online universities",
            "accredited online college courses",
            "accredited online courses",
            "accredited online school",
            "accredited online university",
            "accredited online college",
            "accredited online classes",
            "online accredited universities",
            "accredited online education",
            "accredited online",
            "online accredited colleges",
            "online education accreditation",
            "online phd programs",
            "online phd",
            "phd online",
            "online phd education",
            "online phd degrees",
            "online phd degree",
            "online bachelors degree",
            "online bachelor degree",
            "online bachelors degree programs",
            "bachelor degree online",
            "online bachelor degree programs",
            "bachelors degree online",
            "online bachelor degrees",
            "online bachelors degrees",
            "online bachelors",
            "online bachelors degree education",
            "bachelor degrees online",
            "online bachelor",
            "bachelors degrees online",
            "online bachelor degree education",
            "online college bachelor degree programs",
            "online education bachelor degree programs",
            "online bachelor degree program",
            "distance learning degrees",
            "distance learning degree",
            "distance degree",
            "distance learning degree courses",
            "distance learning master degree",
            "distance education degree",
            "distance learning degree programs",
            "distance degrees",
            "distance education degree online",
            "distance learning masters degree",
            "distance education degrees",
            "distance learning education degree",
            "distance learning degree program",
            "distance education degree programs",
            "distance learning online degree",
            "degrees online accredited distance learning",
            "distance learning online degree programs",
            "online university degrees",
            "university online degrees",
            "online university degree",
            "university degree online",
            "university degrees online",
            "university online degree",
            "online degree university",
            "universities with online degrees",
            "online degree universities",
            "degree online university",
            "universities online degrees",
            "online degrees universities",
            "university degree",
            "online degrees from universities",
            "study online",
            "online studying",
            "study online university",
            "online study programs",
            "online studies",
            "online study",
            "online university studies",
            "best online study",
            "best online universities",
            "best online university",
            "the best online universities",
            "best online universities in the world",
            "best online university in the world",
            "best universities online",
            "the best online university",
            "best university online",
            "online college classes",
            "college classes online",
            "online classes for college",
            "college online classes",
            "online college class",
            "colleges with online classes",
            "colleges that offer online classes",
            "college class online",
            "distance learning universities",
            "distance learning university",
            "university distance learning",
            "online learning university",
            "university online learning",
            "online university learning",
            "online learning universities",
            "distance learning programs",
            "online learning programs",
            "distance learning program",
            "best distance learning programs",
            "accredited distance learning programs",
            "online learning program",
            "best distance learning graduate programs",
            "learning programs online",
            "top distance learning programs",
            "learning to program online",
            "online doctoral programs",
            "online doctorate degrees",
            "online doctorate",
            "doctorate degree online",
            "online doctoral degrees",
            "online doctorate degree",
            "doctorate online",
            "doctoral degrees online",
            "online doctoral degree",
            "online education programs",
            "online education program",
            "best online education programs",
            "education programs online",
            "education online programs",
            "online educational programs",
            "education programs",
            "education program",
            "education online program",
            "top online colleges",
            "top online universities",
            "top online university",
            "top online courses",
            "top online college",
            "top it online colleges",
            "top online universities in the world",
            "top online education programs",
            "top online classes",
            "top online learning sites",
            "top online education",
            "top universities online",
            "online college programs",
            "colleges with online programs",
            "colleges with online degree programs",
            "college online programs",
            "college degree learning online program",
            "colleges that offer online degree programs",
            "best online college programs",
            "online college degree programs",
            "online college degree program",
            "online school programs for college",
            "college programs online",
            "colleges online programs",
            "online college program",
            "online learning courses",
            "home learning courses",
            "online learning course",
            "learning courses",
            "learn courses online",
            "learning courses online",
            "learning online courses",
            "learn online courses",
            "best online learning courses",
            "online course learning",
            "online engineering degree",
            "engineering degree online",
            "online engineering courses",
            "online engineering degrees",
            "engineering degrees online",
            "online graduate programs",
            "online graduate degrees",
            "online graduate courses",
            "online graduate schools",
            "online graduate degree programs",
            "online graduate school",
            "online graduate degree",
            "graduate degrees online",
            "online graduate education",
            "online associates degree",
            "associates degree online",
            "associate degree online",
            "online associate degree",
            "online associates degrees",
            "online associate degree programs",
            "online associate degrees",
            "associate degrees online",
            "distance education university",
            "online university education",
            "online education universities",
            "online education university",
            "university online education",
            "distance education universities",
            "university education online",
            "university education",
            "online degree courses",
            "online degree course",
            "degree courses online",
            "online courses degree",
            "degree online courses",
            "online college education",
            "online education college",
            "online education colleges",
            "college education online",
            "online colleges for education",
            "online colleges education",
            "distance education colleges",
            "online teaching",
            "online teaching degree",
            "teaching online courses",
            "online classes for teaching degree",
            "teaching degree online",
            "online teaching degrees",
            "best online schools",
            "best online school",
            "best school for online classes",
            "best online school programs",
            "best online schools for education",
            "accredited online degree programs",
            "accredited online college degrees",
            "accredited online degrees",
            "online accredited degrees",
            "accredited degree",
            "online degree programs accredited",
            "accredited online degree",
            "accredited online degree program",
            "online accredited degree",
            "accredited online masters degree",
            "accredited online college degree",
            "online study courses",
            "study courses online",
            "study online courses",
            "online studying courses",
            "home study courses",
            "studying online courses",
            "online study course",
            "universities offering online degrees",
            "universities that offer online degrees",
            "colleges that offer online degrees",
            "colleges that offer online courses",
            "universities that offer online courses",
            "university offers online",
            "earn degree online",
            "earn a degree online",
            "earn online degree",
            "earn college degree online",
            "earn your degree online",
            "earn bachelor degree online",
            "earn a college degree online",
            "internet and education",
            "internet education",
            "education internet",
            "education and internet",
            "internet for education",
            "education on the internet",
            "the internet and education",
            "education on internet",
            "online university programs",
            "university online degree programs",
            "online university degree programs",
            "online university degree program",
            "online university program",
            "online continuing education",
            "continuing education online",
            "continue education",
            "continued education",
            "continuing education",
            "distance learning education",
            "online learning education",
            "education learning",
            "education distance learning",
            "online education learning",
            "education learning online",
            "get a degree online",
            "get your degree online",
            "get degree online",
            "get a college degree online",
            "get college degree online",
            "online degree schools",
            "schools that offer online degrees",
            "schools with online degree programs",
            "online schools for education degrees",
            "online school degrees",
            "schools with online degrees",
            "online degree school",
            "online schools degree",
            "education website",
            "online education website",
            "education websites",
            "best education website",
            "e education website",
            "online colleges and universities",
            "online college university",
            "online colleges universities",
            "online college and university",
            "online university college",
            "online course websites",
            "best online course websites",
            "website courses online",
            "best online courses website",
            "best online courses websites",
            "websites for online courses",
            "online university classes",
            "university classes online",
            "university classes",
            "university online classes",
            "online classes university",
            "universities with online classes",
            "free online courses",
            "online courses free",
            "online college courses free",
            "free online course",
            "free online education courses",
            "free online learning courses",
            "online course free",
            "distance learning bachelor degree",
            "bachelor degree distance learning",
            "distance learning bachelor degree programs",
            "distance learning bachelors degree",
            "distance learning bachelor degrees",
            "free online education",
            "free education online",
            "free online degrees",
            "free online university",
            "free online degree",
            "online courses",
            "online course",
            "courses online",
            "online it courses",
            "it courses online",
            "online training courses",
            "online math courses",
            "it online courses",
            "online diploma courses",
            "online training course",
            "online uni courses",
            "online it course",
            "online summer courses",
            "it course online",
            "online courses sites",
            "uni courses online",
            "it online course",
            "online courses with",
            "un online courses",
            "online courses from",
            "online web courses",
            "online courses it",
            "uni online courses",
            "courses from online",
            "a online course",
            "online chemistry courses",
            "online correspondence courses",
            "take online courses",
            "a course online",
            "online course it",
            "online courses in it",
            "take courses online",
            "a courses online",
            "online courses for it",
            "online web course",
            "onlines courses",
            "online a course",
            "online colleges",
            "online college",
            "college online",
            "colleges online",
            "list of online colleges",
            "college lectures online",
            "find online college",
            "find online colleges",
            "online community college",
            "online college search",
            "it college online",
            "online degrees",
            "online degree",
            "degree online",
            "online accounting degree",
            "online business degree",
            "online undergraduate degrees",
            "degrees online",
            "your degree online",
            "online it degree",
            "online finance degree",
            "online biology degree",
            "online math degree",
            "fast online degrees",
            "online english degree",
            "rn degree online",
            "online management degree",
            "online it degrees",
            "aa degree online",
            "online degree search",
            "online ba degree",
            "affordable online degrees",
            "online computer degrees",
            "online paralegal degree",
            "online science degree",
            "online degree completion",
            "online computer science degree",
            "online bs degree",
            "online theology degree",
            "online law degree",
            "online history degree",
            "online nursing degree",
            "law degree online",
            "psychology degree online",
            "online nursing degrees",
            "online journalism degree",
            "online undergraduate degree",
            "online mba degree",
            "affordable online degree",
            "library science degree online",
            "online music degree",
            "online physics degree",
            "it online degree",
            "online computer degree",
            "complete online degrees",
            "online degree accounting",
            "online psychology degrees",
            "online ms degree",
            "mba degree online",
            "online counseling degree",
            "online universities",
            "online university",
            "university online",
            "universities online",
            "it online university",
            "university lectures online",
            "online it university",
            "university of online",
            "from university online",
            "about university online",
            "the online university",
            "new online university",
            "education online",
            "adult education online",
            "online education sites",
            "online higher education",
            "online educations",
            "it education online",
            "about online education",
            "online educational",
            "online it education",
            "online adult education",
            "office online for education",
            "medical education online",
            "online education jobs",
            "online education information",
            "online education site",
            "early childhood education online",
            "education and online",
            "online education resources",
            "benefits of online education",
            "educational online",
            "it online education",
            "educate online",
            "online education training",
            "online computer education",
            "education training online",
            "information about online education",
            "laureate online education",
            "open online education",
            "online education canada",
            "what is online education",
            "online programs",
            "online program",
            "programs online",
            "programs from online",
            "online mba program",
            "online programming courses",
            "online programs that",
            "online program that",
            "the program online",
            "online programs from",
            "it programs online",
            "online education",
            "e-education",
            "correspondence courses",
            "life experience degree",
            "online diploma",
            "internet courses",
            "internet learning",
            "online courseware",
            "internet college",
            "internet classes",
            "degree masters",
            "course line",
            "online diplomas",
            "course on line",
            "internet degree",
            "courses from",
            "class on line",
            "education line",
            "internet colleges",
            "on line learning",
            "on line courses",
            "masters education",
            "u online",
            "distant learning",
            "high school education",
            "phd education",
            "diploma online",
            "correspondence schools",
            "virtual education",
            "correspondence course",
            "free education",
            "study at home",
            "technology education",
            "on line education",
            "teacher education",
            "home education",
            "online uni",
            "learning classes",
            "on line colleges",
            "internet course",
            "education sites",
            "education and training",
            "graduate education",
            "career education",
            "internet for learning",
            "on line classes",
            "life experience degrees",
            "education journals",
            "internet school",
            "internet and learning",
            "adult education",
            "education articles",
            "education resources",
            "math education",
            "with online lessons",
            "online ed",
            "internet universities",
            "gifted education",
            "on line schools",
            "on line school",
            "on line lessons"
        ]
    };
    //console.log(searchArrays.fitness);
    var searchTerms;

    if (searchArrays[_topic]) {
        searchTerms = searchArrays[_topic];
    } else {
        searchTerms = searchArrays.fitness;
    }

    console.log(searchTerms);

    var _index = Math.floor((Math.random() * searchTerms.length) + 1);

    if (_formArray[0]) {
        _formArray[0].q.value = searchTerms[_index];
        _formArray[0].submit();
    }

})